### ISSUE TITLE
Calculate the error rates of the simulator

### ISSUE THREAD

**Issue by hansyuan** [EMSTrack/Algorithms#13]
Need to check that the speeds and times make sense for travel times. 

We currently use kd-trees to find the nearest point, but we don't consider the error distance between the generated point and the existing point we use from the travel times. 

Need: Since it's a simulator, we want to know about drastically incorrect travel times. 
Solution1: ~Data Distance / Real Distance = Percentage Error. (100% is not necessarily correct!)~
Solution2: Data Distance / Real Distance * 100 - 100 = Percentage Error. 
(0% means the line between the two sets of two points are the same, not that the travel times are the same!)
Assumption: travel times with the same distance have negligible error.

**Comment by hansyuan** [comment]
This is implemented in the simulator and can be seen in the print statements: `distance difference`.

0% difference means the distance between two geo points p1_sim and p2_sim are the same distance between p1_real and p2_real. This does not guarantee that the travel time are equal, but it gives us a metric to find extremely bad inaccuracies. 

Example, 7000% means the simulator distance was 7000% that of the real distance. This occurred 2/7000 times that the TravelTimes generator was invoked. Otherwise, the median and average were very close to 0%. 

```
$ ./error.py
count: 7000
min: -94.81
max: 6963.32
avg: 1.2881414285714285
median: -0.75
```

**Comment by hansyuan** [comment]
```
In [6]: errors
Out[6]:
[6963.32,
 6963.32,
 1148.47,
 1036.11,
 411.86,
 411.86,
 250.38,
 250.38,
 130.68,
 102.43,
 96.42,
 94.67,
 91.34,
 89.9,
 86.16,
 85.58,
```

Decreasing sorted error rates.

**Comment by mcdeoliveira** [comment]
Your current formula

error = (real - data) / data

has a problem when data is very small. If you think that will be a constant thing you can regularize it as follows:

error = (real - data) data / (data^2 + epsilon)

where epsilon is small. If epsilon = 0 then the two formulas are the same. The difference is when data is small. Note that the regularized formula gives a zero error when data = 0 whereas the original formula diverges.

**Comment by hansyuan** [comment]
Another useful thing to do: 

- Visualize the points from data versus the actual points

**Comment by hansyuan** [comment]
Got some new numbers from accumulating some of the error calculations: 

```count: 7000
min: -936.51
max: 2529.47
avg: 23.903584285714285
median: 4.56 ```

**Comment by hansyuan** [comment]
Visualized the error points:

![image](https://user-images.githubusercontent.com/20445239/51808196-90446500-2245-11e9-9d69-3a0d310e7734.png)

```
set_points(data['real_locs'],  style="bo")
set_points(data['sim_locs'],  style="ro")
```

Blue = "Real" locations meaning they are the coordinates the simulator is using in its event history. 
Red = Destination points from the travel times.

**Comment by hansyuan** [comment]
![image](https://user-images.githubusercontent.com/20445239/51866422-cd6c2e00-22fd-11e9-9ad6-faa3faa65b1e.png)

The points outside the polygon are bases. 

Still should look at visualizing the errors

**Comment by hansyuan** [comment]
![image](https://user-images.githubusercontent.com/20445239/51947799-f9a9ac80-23da-11e9-8f37-2d7f17eccd97.png)

7000 bases x 7000 demands 
400 cases per simulator run 
took probably half an hour each run

**Comment by hansyuan** [comment]
![image](https://user-images.githubusercontent.com/20445239/51949979-a720be00-23e3-11e9-9a07-79f1cb38aa1d.png)

48 bases x 10 demand points

**Comment by thl024** [comment]
Discovered a potential reason the errors were so large:

<img width="375" alt="screen shot 2019-01-30 at 12 33 55 pm" src="https://user-images.githubusercontent.com/10791406/52010829-549adc80-248b-11e9-80c4-f48a2dfd9d68.png">

In this example, the distance between the generated incident and the hospital is very close to 0. However, since the travel times file is non-symmetric and maps bases -> demand, the travel times was computing a distance between the closest base to the incident and the closest demand point to the hospital. This distance is low, but the error blows up because the real dist is much lower.

@hansyuan Can solve by modifying epsilon?

**Comment by hansyuan** [comment]
Tim found the bug, it’s in two parts

(1) there was a bug in the simulator which Tim fixed
(2) my change to use the normalized formula _never made it into the branch commits_

**Comment by thl024** [comment]
Regularized scenario: error = (real - data) data / (data^2 + epsilon)
epsilon is low

This scenario protects against situations where data is 0. In scenarios where data is very small and non-zero, error ends up being very high:

e.g. Travel Times dist = real = 50 meters
Real Distance = data = 1 meters
epsilon = 0.001

Error = ~49 = 4900%

This is actually expected because the travel times dist is 50 times larger than real dist. Thus, given our travel times input file, error calculation is functioning properly and large errors may be expected in the simulation.

**Comment by hansyuan** [comment]
Nice! Thanks for confirming the error calculations against the actual distances.
