### ISSUE TITLE
Modify case record output to be compatible as an input into the simulation

### ISSUE THREAD

**Issue by thl024** [EMSTrack/Algorithms#35]

**Comment by hansyuan** [comment]
from tim

CSVCaseSet implemented. I subclassed because it was the simplest, fastest solution at the moment. This class will read a case set from file and supports different headers if necessary (you will not need this functionality right now). By default, the class will look for the following headers:

"id", "date", "longitude", "latitude", "priority"

Those fields are the exact names of the fields produced from the simulation output. You should be able to generate a cases.csv from the simulation output and feed that in directly into the CSV Case Set.

Example yaml of CSVCaseSet:

cases:
class: ems.datasets.case.csv_case_set.CSVCaseSet
filename: ./examples/cases.csv
event_generator: $event_generator

**or**

cases:
class: ems.datasets.case.csv_case_set.CSVCaseSet
filename: ./examples/cases.csv
headers: ["custom id column name", "custom date column name", "custom longitude column name", "custom latitude column name", "custom priority column name"]
event_generator: $event_generator
